apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-certs-pvc
  namespace: es-secure
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
