apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  namespace: es-secure
spec:
  serviceName: elasticsearch-data
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
      role: data
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: elasticsearch
        image: 918905608842.dkr.ecr.eu-west-1.amazonaws.com/aws-es-node-img-repository:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: es-common-config
        - secretRef:
            name: es-credentials
        env:
        - name: ES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ES_NODE_ROLES
          value: "data,remote_cluster_client"
        - name: ES_CERTS_PATH
          value: "/home/es_user/elasticsearch/config/certs"
        volumeMounts:
        - name: data
          mountPath: /home/es_user/elasticsearch/data
        - name: logs
          mountPath: /home/es_user/elasticsearch/logs
        - name: certs
          mountPath: /home/es_user/elasticsearch/config/certs
          readOnly: false
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
            #livenessProbe:
            #  exec:
            #    command:
            #    - /bin/bash
            #    - -c
            #    - 'curl -k -s -u elastic:${ES_PASS} https://localhost:9200/_cluster/health?local=true | grep -q "green\|yellow"'
            #  initialDelaySeconds: 60
            #  periodSeconds: 10
            #  timeoutSeconds: 5
            #  failureThreshold: 3
            #  successThreshold: 1
        ##readinessProbe:
        ##  httpGet:
        ##    path: /
        ##    port: 9200
        ##    scheme: HTTPS
        ##  initialDelaySeconds: 30
        ##  periodSeconds: 10
      volumes:
      - name: certs
        persistentVolumeClaim:
          claimName: es-certs-pvc
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp3
      resources:
        requests:
          storage: 200Mi
  - metadata:
      name: logs
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp3
      resources:
        requests:
          storage: 100Mi
