apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: es-secure
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: es-secure
spec:
  clusterIP: None
  selector: # filter of the pods to which the service applies
    app: elasticsearch
    role: data
  ports:
  - name: transport
    port: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-http
  namespace: es-secure
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: es-secure
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 5601
